spring:
  application:
    name: auth-service

  redis:
    host: localhost
    port: 6379

  rabbitmq:
    host: localhost
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

rabbitmq:
  notification:
    exchange: notificationExchange
    routingkey: notifyUser

