spring:
  application:
    name: user-service

  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/userservicedb
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: mysql@123


  cloud:
    config:
      import-check:
        enabled: false
    compatibility-verifier:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9002

jwt:
  secret: Zm9vYmFyMTIzNDU2Nzg5MGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6
