server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false   # This Eureka Server will not register itself
    fetch-registry: false         # This Eureka Server will not fetch registry