server:
  port: 8888

spring:
  application:
    name: Config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/simrandhiman-21/LearningManagamentSystem
          clone-on-start: true